# Site settings
title: 林兴洋的空间站
SEOTitle: 林兴洋的空间站 | linxingyang
header-img: img/home/bg-tags.jpg
email: linxingy@foxmail.com
description: "林兴洋, 林兴洋的主页, 林兴洋的博客, java"
keyword: "林兴洋, 林兴洋的主页, 林兴洋的博客"
url: "http://linxingyang.net"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

author: 林兴洋
moto: 世间千般好
icon-img: /img/favicon.ico

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
# weibo_username:     linxingyang
# zhihu_username:     huxpro
github_username:    linxingyang
# twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  


# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
# plugins: [jekyll-paginate, jekyll-toc]
plugins:
  - jekyll-paginate
#  - jekyll-toc # github page doesn't support jeyll-toc, you can simple use toc *{ content }
# or just like the next line, use catalog: true to have a sidebar catalog

# article TOC
catalog: true

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# git talks https://github.com/gitalk/gitalk
# more than 50KB+ resources(js/css and so on).
plugin-gitalk-use: false

# busuanzi web visit counter http://busuanzi.ibruce.info/.
plugin-busuanzi-use: true

# my personal web visit counter, just for test, don't use it.
plugin-mycounter-use: false

# Analytics settings
# Baidu Analytics 
ba_track_id: 248a1d751848090a4aeb3a0e92fe605e

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "生命不息，学习不止"
sidebar-avatar: /img/avatar/fd-small.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 5              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
# friends: [
#    {
#       title: "Su",
#       href: "http://su.gallery/"
#    },{
#        title: "乱序",
#        href: "http://mida.re/"
#    },{
#        title: "前端外刊评论",
#        href: "http://qianduan.guru/"
#    }
#]


# note
# relative-tags 不要引入会有重复的文章的标签
